#!/usr/bin/env bash
#Displays a loop from 1 to 10 and at 4th bad luck, good luck on 8th, Best School otherwise

count=1
while [ "$count" -le 10 ]; do
	if [ "$count" -eq 4 ]; then
		echo "bad luck"
	elif [ "$count" -eq 8 ]; then
		echo "good luck"
	else 
		echo "Best School"
	fi
	((count++))
done
