#!/usr/bin/env bash
#Displaying numbers from 1 to 20 with 'bad luck from China' on 4th line, 'bad luck from Japan' on 9th line, bad luck from Italy' on 17th loop

count=1
while [ "$count" -le 20 ]; do
	echo "$count"
	case "$count" in
		4) echo "bad luck from China" ;;
		9) echo "bad luck from Japan" ;;
		17) echo "bad luck from Italy" ;;
	esac
	((count++))
done
